In [5]:
import pandas as pd

In [12]:
df = pd.read_csv("D:\\moringa_school\\CapStone\\final_project\\Data\\reduced_reddit.csv")

In [13]:
df

,title,body,upvotes,created_utc,num_comments,label
0,Day 18 of doing 50 push-ups,NaN,4.0,1.619357e+09,4.0,0.0
1,There isn’t a better feeling than finishing yo...,Then your teacher hits you with that “ Good jo...,7.0,1.554103e+09,NaN,0.0
2,LMAOOO I can only get this guy to talk to me i...,Yeahhh maybe not babe,4.0,1.649342e+09,12.0,0.0
3,This isn't going to work out,NaN,236.0,1.417630e+09,33.0,0.0
4,Am I the only guy who found it hurtful as a ch...,\n\nLike... why? How is that funny? How does ...,6.0,1.569280e+09,4.0,0.0
...,...,...,...,...,...,...
98821,Has anyone ever had any problems with gangs?,I don't care if my grammer isn't good so dont ...,8.0,1.558082e+09,1.0,1.0
98822,"Moments away from killing myself, not even bot...","I don't want to talk about my problems, I don'...",12.0,1.350754e+09,8.0,1.0
98823,I've grown used to being like this for years.,"I'm not suicidal at the moment, in fact I feel...",14.0,1.432074e+09,4.0,1.0
98824,This speech from The Lord of the Rings really ...,"""It's like in the great stories, Mr. Frodo. Th...",323.0,1.355673e+09,28.0,1.0
98825,I just don't know....,I have never thought that I will end up in thi...,5.0,1.328355e+09,3.0,1.0

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 98826 entries, 0 to 98825
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         98826 non-null  object
 1   body          80371 non-null  object
 2   upvotes       98826 non-null  float64
 3   created_utc   98826 non-null  float64
 4   num_comments  94297 non-null  float64
 5   label         98826 non-null  float64
dtypes: float64(4), object(2)
memory usage: 4.5+ MB